name: Downstream

on:
  pull_request:
    branches: [ 'release-*' ]

jobs:

  downstream:
    name: Unit Test
    strategy:
      fail-fast: false # Keep running if one leg fails.
      matrix:
        include:
          - org: openshift
            repo: knative-serving
            branch: release-next
          - org: openshift
            repo: knative-eventing
            branch: release-next
          - org: openshift
            repo: knative-client
            branch: release-next
          - org: openshift-knative
            repo: eventing-kafka
            branch: release-next

    runs-on: ubuntu-latest
    env:
      GOPATH: ${{ github.workspace }}
    steps:
    - name: Set up Go 1.16.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - name: Checkout Upstream
      uses: actions/checkout@v2
      with:
        path: ./src/knative.dev/${{ github.event.repository.name }}
    - name: Checkout Downstream
      uses: actions/checkout@v2
      with:
        repository: ${{ matrix.org }}/${{ matrix.repo }}
        path: ./src/${{ matrix.org }}/${{ matrix.repo }}
        ref: ${{ matrix.branch }}
    - name: Test Downstream
      uses: knative-sandbox/actions-downstream-test@v1
      with:
        upstream-module: knative.dev/${{ github.event.repository.name }}
        downstream-module: ${{ matrix.org }}/${{ matrix.repo }}
