name: Test

on:

  push:
    branches: [ 'release-*' ]

  pull_request:
    branches: [ 'release-*' ]

jobs:

  test:
    name: Unit Tests
    strategy:
      matrix:
        go-version: [1.16.x]
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Check out code
        uses: actions/checkout@v2

      - name: Test
        run: go test -race ./...
